language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.4
  - 5.6

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=0
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/c3-cloudfront-clear-cache/
    - GH_REF: https://github.com/megumiteam/c3-cloudfront-clear-cache.git
    - secure: "6J8cCLa3wFGghhTSJw+GRHm42q/hWDc83LMEX6NgA/KYoQqhJcPm7fWF0ABBxUeAY+Uj3HaLq8SF2J5rgRIujKKgZonwH3UR6uKQB5L6VnXiHgaqpFPxHXEgAZa/xR+JKpS9+jM+mWamkJN/sSfcO9Yc+XpQjb4qvk7ZQM0gIA4zFnljMA6hk4oGc+0LUwYDBkgLa++kXb6jtGI3OmriGwyF7MfzE9cdHRc08YlLvRuKySKw4UlbzyttRS/wPEKy39KDwSBlXfOY6aiRnuCIwboIXQl/s2IfUJPpfSZCcxAuy2HWNWtv8otm5+QraTdM+0MJG8Ht5mL/JiSPQ7vTlSOOVVqw9hyR0/hsgOxp7huCaPj8ynDb4nTHs31NGE1njrib1QdIiA8scBHS3cu+SeU+RuimSw5nuniY5xge0mOaOz7S4LQCQJ59AKLTeMzevhMf2H/IuleMkL65/DseNuzUG1NncNABArzDwqJ5ITq/K3pnQSkqpqWgVkSIFeAUpZxHaJuNf316bBmcHAvVN0fpanjQdN6ZFq6VPPAZEDX0o/lR9BZuwiaV6MgGrAXUXQGNrvcMXHPEGv+NwidovUno46UsKx79oRRcTum4Dx+WO6yKeJtCkRIk9C0Aq3tB9pqe+EVSfLfsVAxDf/IOM8czGD7ptkEdfAyI4bF4PGw="
    - secure: "CLm4wVNnunn8LZORsjhCk+ZXKiVj04jTTeAksQJvvyWIO5nj0qXfOTWd417MWcEzwkdet1jkmKvyVseLP8tqIln6ANzmYslqSki0YRC8EiSmS1KYaTlcZs34yL7UJjDxhjUDn6zT3RMWLelCl3rytfLJzl2ryfSgaMy4jf7yyZycbfCjhSQ8A3lK7Eq2aeLEmd6LINj6UlMa464MwkyHfaPzQmrl31hdhtNtf1dmv76dmcy9V7Vr5ITYanSpoIcEjVg3PETf02zw0TkPoVP1A1zHWl+Yyunj/lgMcBqqys0v/8d0acEcr4SAsF55mO+gdy67akeBTB4V2tBjenDXlmPTJ5Ji1jidHGcLRDErsbXlYXKSRVkhrlkEnXw72FisZYHuR8t5CXyTxxDv9UqCbsBoVkXTz/+k3kKi0d0n51/0x1c1OllgBK+ZZhDadrn81HPCVwQ4E0eJrE8p/llYMYmxfZpITSh3lfISS/jB1duW/NVj836gTAFkhOcCiFerOXSwNqk7w7ESJ/HNWHTp6fpIt128RVAbM81P3dqYWOe2Nt8By9lTf87WHOVlVDilf1AdIjUobM/v/0TtsjdswzuJLwLURPsCFgwXV5Ku6HT/UezCHF0Hcx14n86i1ApxV2D34Eghe8hk0o9g00bx9pMWpd6J64NUvU0i6j9MyII="
    
before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - bash bin/build.sh

script: phpunit

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
