language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.4
  - 5.6

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=0
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/c3-cloudfront-clear-cache/
    - GH_REF: https://github.com/megumiteam/c3-cloudfront-clear-cache.git
    - secure: "xxxx"

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - bash bin/build.sh

script: phpunit
secure: "6J8cCLa3wFGghhTSJw+GRHm42q/hWDc83LMEX6NgA/KYoQqhJcPm7fWF0ABBxUeAY+Uj3HaLq8SF2J5rgRIujKKgZonwH3UR6uKQB5L6VnXiHgaqpFPxHXEgAZa/xR+JKpS9+jM+mWamkJN/sSfcO9Yc+XpQjb4qvk7ZQM0gIA4zFnljMA6hk4oGc+0LUwYDBkgLa++kXb6jtGI3OmriGwyF7MfzE9cdHRc08YlLvRuKySKw4UlbzyttRS/wPEKy39KDwSBlXfOY6aiRnuCIwboIXQl/s2IfUJPpfSZCcxAuy2HWNWtv8otm5+QraTdM+0MJG8Ht5mL/JiSPQ7vTlSOOVVqw9hyR0/hsgOxp7huCaPj8ynDb4nTHs31NGE1njrib1QdIiA8scBHS3cu+SeU+RuimSw5nuniY5xge0mOaOz7S4LQCQJ59AKLTeMzevhMf2H/IuleMkL65/DseNuzUG1NncNABArzDwqJ5ITq/K3pnQSkqpqWgVkSIFeAUpZxHaJuNf316bBmcHAvVN0fpanjQdN6ZFq6VPPAZEDX0o/lR9BZuwiaV6MgGrAXUXQGNrvcMXHPEGv+NwidovUno46UsKx79oRRcTum4Dx+WO6yKeJtCkRIk9C0Aq3tB9pqe+EVSfLfsVAxDf/IOM8czGD7ptkEdfAyI4bF4PGw="

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
