language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
    - php: 7
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.4 WP_MULTISITE=0
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/c3-cloudfront-clear-cache/
    - GH_REF: https://github.com/megumiteam/c3-cloudfront-clear-cache.git
    - secure: "XpDlMFkdvpk9k7UmwgZ/XpCOQQOQCZNCNGnEQMw3gk/j7chhFdgGCGEFRsHCdJED9qNuuZ3M2TwQQWJfUYoasdr8XA04S5PkTFO5xulEtWsy1y16khj12EbhVm4xDxcKWfD+f4shOpGxKiCP0Csmru9FWbDLI9W+scYJbR3Dq1/utG6TNoN3sC95j6CHrkjOWKt4jDc4Ti9Nl9mc+Eb5Heauvbl4Ors4nL11fQhdMTO1xjf7071FiaEwBZ0BekAbHgoI/915VqOxKbFsbQ9YLzmLQrnLI3qMeHcOFA3o3UDSb2MBokQMZ9B5kuRglSYvOBRPdlQ9xDy4SdEEq1Y288X5xwYQwNnZylE9FSrpOTrGqgcmGGXCZUYC8usZw6PhvZF1vaucYX49jt6l3TmCa6bnqKPzlHQvHAi+6VemqiGbufvPH8aDKSHldRxfazhok3SLpAOkjf8Xc56S0AIYoRNioTH01QdpTsRwJVavLk6LV5yGo8W1dgPdo1I1tPtDqzsRn5USw4W570TyR0qOAaabcbpUZMlaQ0/K7BqJM0oZ1ZH8hFTQVNzneLMSPEMSF1H1inuU1W+ShCx1jFcpAoAJsB6YymPfAGXiLPEes6e0sT5epQNgVKh5EbnI8r9a5gXMWQMeGSoDIz25ZlWO2ZOqfO19m4D4oydkntAnp+8="

before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - bash bin/build.sh

script: phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
